define longfade = Fade(2.5, 0, 2.5)
define blinds = ImageDissolve(im.Tile("blindstile.png"), 3.5, 8)
define blinds_1 = ImageDissolve(im.Tile("blindstile.png"), 3.5, 8)
define smoke = Dissolve(1)
define fastdissolve = Dissolve(0.2)
define slowdissolve = Dissolve(5.5)
define longflash = Fade(1, 0, 1, color="#fff")
define longflash2 = Fade(3.5, 0, 1, color="#fff")
define flash = Fade(.25, 0, .75, color="#fff")

init:
    ### 
    transform zoom_btn:
        zoom 0.6 xanchor 0.63 yanchor 50
        
    image delete_btn_idle = "gui/del_idle.png"
    image delete_btn_hover = "gui/del_hover.png"

    ### TEST images
    image test_image = "images/interface_images/Thinking.png"

    ### Time images
    image time_of_day = ConditionSwitch(
        "timeofdaycounter == 1", "Morning.png",
        "timeofdaycounter == 2", "LateMorning.png",
        "timeofdaycounter == 3", "Afternoon.png",
        "timeofdaycounter == 4", "Evening.png",
        "timeofdaycounter == 5", "Night.png"
        )

    image day_of_week = ConditionSwitch(
        "daycounter == 1", "Mon.png",
        "daycounter == 2", "Tue.png",
        "daycounter == 3", "Wed.png",
        "daycounter == 4", "Thu.png",
        "daycounter == 5", "Fri.png",
        "daycounter == 6", "Sat.png",
        "daycounter == 7", "Sun.png"
        )

    ### pc gallery images
    image bg Desktop_1 = "images/interface_images/pc_gallery_images/Pc_bg.png"
    image bg DesktopFolder_1 = "images/interface_images/pc_gallery_images/Pc_gal_bg.png"
    image bg Desktop_login = "images/interface_images/pc_gallery_images/Pc_bg_login.png"

    image bg MomInShower03 = "MomInShower03.png"
    image bg MomMastBateBath03 = "MomMastBateBath03.png"

    image bg LaurenInShower03 = "LaurenInShower03.png"
    image bg LaurenMastBateBath03 = "LaurenMastBateBath03.png"

    image bg PeekSidneyDressingMobile = "PeekSidneyDressingMobile.png"
    image bg SidneyInShower03 = "SidneyInShower03.png"
    image bg SidneyMastBateBath03 = "SidneyMastBateBath03.png"

    ### inventory images
    image bg Inventory = "images/interface_images/inventory_images/inventory.png"

    ### main menu images
    image GameMenu:
        "gui/game_menu.webp"

#        $ renpy.transition(longfade)

    ### shopping gallery
    image bg OnlineShopping = "images/interface_images/shopping_gallery_images/OnlineShopping.png" ### hardnLong for screen
    image bg OnlineShopping_1 = "images/interface_images/shopping_gallery_images/OnlineShopping_1.png" ### hardnLong with Ryan
    image bg OnlineShopping_2 = "images/interface_images/shopping_gallery_images/OnlineShopping_2.png" ### hardnLong for first time shopping
    image bg OnlineShopping_3 = "images/interface_images/shopping_gallery_images/OnlineShopping_3.png" ### hardnLong if failedsneakattempt

    image advertising_banner_patreonsafe:
        "images/interface_images/shopping_gallery_images/advertising_banner_1.png"
        pause 1.0
        "images/interface_images/shopping_gallery_images/advertising_banner_2.png"
        pause 1.0
        "images/interface_images/shopping_gallery_images/advertising_banner_3_patreonsafe.png"
        pause 1.0
        repeat

    image advertising_banner_SubStar_patreonsafe:
        "images/interface_images/shopping_gallery_images/BannerSubStar_01.png"
        pause 1.0
        "images/interface_images/shopping_gallery_images/BannerSubStar_02.png"
        pause 1.0
        "images/interface_images/shopping_gallery_images/BannerSubStar_03_patreonsafe.png"
        pause 1.0
        repeat

    image advertising_banner:
        "images/interface_images/shopping_gallery_images/advertising_banner_1.png"
        pause 1.0
        "images/interface_images/shopping_gallery_images/advertising_banner_2.png"
        pause 1.0
        "images/interface_images/shopping_gallery_images/advertising_banner_3.png"
        pause 1.0
        repeat

    image advertising_banner_SubStar:
        "images/interface_images/shopping_gallery_images/BannerSubStar_01.png"
        pause 1.0
        "images/interface_images/shopping_gallery_images/BannerSubStar_02.png"
        pause 1.0
        "images/interface_images/shopping_gallery_images/BannerSubStar_03.png"
        pause 1.0
        repeat

    ### PC gallery
    image Pc_gal_Jacky_Folder-Desktop-icon_idle = "images/interface_images/pc_gallery_images/Pc_gal_Jacky_Folder-Desktop-icon_idle.png"
    image Pc_gal_Lauren_Folder-Desktop-icon_idle = "images/interface_images/pc_gallery_images/Pc_gal_Lauren_Folder-Desktop-icon_idle.png"
    image Pc_gal_Sidney_Folder-Desktop-icon_idle = "images/interface_images/pc_gallery_images/Pc_gal_Sidney_Folder-Desktop-icon_idle.png"
    image Pc_gal_Camille_Folder-Desktop-icon_idle = "images/interface_images/pc_gallery_images/Pc_gal_Camille_Folder-Desktop-icon_idle.png"
    image Pc_gal_Mandy_Folder-Desktop-icon_idle = "images/interface_images/pc_gallery_images/Pc_gal_Mandy_Folder-Desktop-icon_idle.png"

    ### cosplay gallery
    image bg CosplayKitchen01 = "CosplayKitchen01.webp"
    image bg RegisterCosplaySite = "images/interface_images/cosplay_gallery_images/RegisterCosplayHeavenSite.png"
    image bg CosplaySite = "images/interface_images/cosplay_gallery_images/CosplayHeavenSite.png"
    image bg CosplayWarehouse20 = "images/interface_images/cosplay_gallery_images/CosplayWarehouse20.png" ### CosplayHeaven

    image sold_banner:
        "images/interface_images/cosplay_gallery_images/inv_sold.png"
        pause  0.8
        Null()
        pause  0.8
        "images/interface_images/cosplay_gallery_images/inv_sold.png"
        repeat

    ### booble screen
    image bg CosplayWarehouse19 = "images/interface_images/booble_images/CosplayWarehouse19.png" ### Booble

    ### phone images
    image phoneExitIdle = im.Scale("images/interface_images/phone_screen_images/Phone_exit_idle.png", 20, 50)
    image phoneExitHover = im.Scale("images/interface_images/phone_screen_images/Phone_exit_hover.png", 20, 50)

    ### Game images
    image bg bathroom01 = "bathroom01.webp"
    image bg BathroomDoor = "BathroomDoor.webp"
    image bg BathroomDoorNight = "BathroomDoorNight.webp"
    image bg BlurryWhite = "BlurryWhite.jpg"
    image bg CaughtBySidney01 = "CaughtBySidney01.webp"
    image bg CaughtBySidney02 = "CaughtBySidney02.webp"
    image bg CityMap01 = "CityMap01.webp"
    image bg CityMapNight = "CityMapNight.webp"
    image bg Classroom01 = "Classroom01.webp"
    image bg Classroom02 = "Classroom02.webp"
    image bg Classroom03 = "Classroom03.webp"
    image bg Classroom04 = "Classroom04.webp"
    image bg Classroom05 = "Classroom05.webp"
    image bg Classroom06 = "Classroom06.webp"
    image bg Classroom07 = "Classroom07.webp"
    image bg Classroom08 = "Classroom08.webp"
    image bg Classroom09 = "Classroom09.webp"
    image bg Classroom10 = "Classroom10.webp"
    image bg Classroom1stPerson01 = "Classroom1stPerson01.webp"
    image bg Classroom1stPerson02 = "Classroom1stPerson02.webp"
    image bg Classroom1stPerson03 = "Classroom1stPerson03.webp"
    image bg ClassroomStrip01 = "ClassroomStrip01.webp"
    image bg ClassroomStrip02 = "ClassroomStrip02.webp"
    image bg ClassroomStrip03 = "ClassroomStrip03.webp"
    image bg ClassroomStrip04 = "ClassroomStrip04.webp"
    image bg ClassroomStrip05 = "ClassroomStrip05.webp"
    image bg ClassroomStrip06 = "ClassroomStrip06.webp"
    image bg ClubEntrance01 = "ClubEntrance01.webp"
    image bg ClubEntrance02 = "ClubEntrance02.webp"
    image bg CosplayIntro01 = "CosplayIntro01.webp"
    image bg CosplayIntro02 = "CosplayIntro02.webp"
    image bg CosplayIntro03 = "CosplayIntro03.webp"
    image bg CosplayIntro04 = "CosplayIntro04.webp"
    image bg CosplayIntro05 = "CosplayIntro05.webp"
    image bg CosplayIntro06 = "CosplayIntro06.webp"
    image bg CosplayIntro07 = "CosplayIntro07.webp"
    image bg CosplayIntro08 = "CosplayIntro08.webp"
    image bg CosplayIntro09 = "CosplayIntro09.webp"
    image bg CosplayWakeMe01 = "CosplayWakeMe01.webp"
    image bg CosplayWakeMe02 = "CosplayWakeMe02.webp"
    image bg CosplayWakeMe03 = "CosplayWakeMe03.webp"
    image bg CosplayWakeMe04 = "CosplayWakeMe04.webp"
    image bg CosplayWarehouse01 = "CosplayWarehouse01.webp"
    image bg CosplayWarehouse02 = "CosplayWarehouse02.webp"
    image bg CosplayWarehouse03 = "CosplayWarehouse03.webp"
    image bg CosplayWarehouse04 = "CosplayWarehouse04.webp"
    image bg CosplayWarehouse05 = "CosplayWarehouse05.webp"
    image bg CosplayWarehouse06 = "CosplayWarehouse06.webp"
    image bg CosplayWarehouse07 = "CosplayWarehouse07.webp"
    image bg CosplayWarehouse08 = "CosplayWarehouse08.webp"
    image bg CosplayWarehouse09 = "CosplayWarehouse09.webp"
    image bg CosplayWarehouse10 = "CosplayWarehouse10.webp"
    image bg CosplayWarehouse11 = "CosplayWarehouse11.webp"
    image bg CosplayWarehouse12 = "CosplayWarehouse12.webp"
    image bg CosplayWarehouse13 = "CosplayWarehouse13.webp"
    image bg CosplayWarehouse14 = "CosplayWarehouse14.webp"
    image bg CosplayWarehouse15 = "CosplayWarehouse15.webp"
    image bg CosplayWarehouse16 = "CosplayWarehouse16.webp"
    image bg CosplayWarehouse17 = "CosplayWarehouse17.webp"
    image bg CosplayWarehouse18 = "CosplayWarehouse18.webp"
    image bg CosplayWarehouse19 = "CosplayWarehouse19.webp"
    image bg CosplayWarehouse20 = "CosplayWarehouse20.webp"
    image bg CosplayWarehouse21 = "CosplayWarehouse21.webp"
    image bg CosplayWarehouse22 = "CosplayWarehouse22.webp"
    image bg CosplayWarehouse23 = "CosplayWarehouse23.webp"
    image bg CosplayWarehouse24 = "CosplayWarehouse24.webp"
    image bg CoverUp01 = "CoverUp01.jpg"
    image bg CoverUp02 = "CoverUp02.webp"
    image bg CreepShot01 = "CreepShot01.webp"
    image bg CreepShot02 = "CreepShot02.webp"
    image bg CreepShotLauren01 = "CreepShotLauren01.webp"
    image bg Deliveries = "Deliveries.webp"
    image bg Desktop = "Desktop.webp"
    image bg DesktopFolder = "DesktopFolder.webp"
    image bg DinnerAttnLauren01 = "DinnerAttnLauren01.webp"
    image bg DinnerAttnLauren02 = "DinnerAttnLauren02.webp"
    image bg DinnerAttnLauren03 = "DinnerAttnLauren03.webp"
    image bg DinnerAttnMom01 = "DinnerAttnMom01.webp"
    image bg DinnerAttnMom02 = "DinnerAttnMom02.webp"
    image bg DinnerAttnMom03 = "DinnerAttnMom03.webp"
    image bg DinnerAttnRyan01 = "DinnerAttnRyan01.webp"
    image bg DinnerAttnRyan02 = "DinnerAttnRyan02.webp"
    image bg DinnerAttnRyan03 = "DinnerAttnRyan03.webp"
    image bg DishesNoMom01 = "DishesNoMom01.webp"
    image bg DishesNoMom02 = "DishesNoMom02.webp"
    image bg DoingDishesMom01 = "DoingDishesMom01.webp"
    image bg DoingDishesMom02 = "DoingDishesMom02.webp"
    image bg DoingDishesMom03 = "DoingDishesMom03.webp"
    image bg DoingDishesWLauren01 = "DoingDishesWLauren01.webp"
    image bg DoingDishesWLauren02 = "DoingDishesWLauren02.webp"
    image bg DrinkingKitchenMom = "DrinkingKitchenMom.webp"
    image bg DrunkMomRoom01 = "DrunkMomRoom01.webp"
    image bg DrunkMomRoom02 = "DrunkMomRoom02.webp"
    image bg DrunkMomRoom03 = "DrunkMomRoom03.webp"
    image bg DrunkMomRoom04 = "DrunkMomRoom04.webp"
    image bg DrunkMomRoom05 = "DrunkMomRoom05.webp"
    image bg DrunkMomRoom06 = "DrunkMomRoom06.webp"
    image bg FamilyPhotoAdjusted = "FamilyPhotoAdjusted.webp"
    image bg FamilyRoom01 = "FamilyRoom01.webp"
    image bg FirstDinner = "FirstDinner.webp"
    image bg FrontDoor01 = "FrontDoor01.webp"
    image bg FrontDoor02 = "FrontDoor02.webp"
    image bg FrontDoor03 = "FrontDoor03.webp"
    image bg FrontDoor04 = "FrontDoor04.webp"
    image bg FrontDoor05 = "FrontDoor05.webp"
    image bg FrontDoor06 = "FrontDoor06.webp"
    image bg FrontDoor07 = "FrontDoor07.webp"
    image bg FrontDoor08 = "FrontDoor08.webp"
    image bg FrontDoor09 = "FrontDoor09.webp"
    image bg FrontDoor10 = "FrontDoor10.webp"
    image bg FrontDoor11 = "FrontDoor11.webp"
    image bg HangingInRoomLauren01 = "HangingInRoomLauren01.webp"
    image bg HangingInRoomLauren02 = "HangingInRoomLauren02.webp"
    image bg HangingInRoomLauren03 = "HangingInRoomLauren03.webp"
    image bg HangingInRoomLauren04 = "HangingInRoomLauren04.webp"
    image bg HangingInRoomLauren05 = "HangingInRoomLauren05.webp"
    image bg HangingInRoomLauren06 = "HangingInRoomLauren06.webp"
    image bg Hardalong = "Hardalong.webp"
    image bg HardnlongVersion2 = "HardnlongVersion2.webp"
    image bg ImageMapLauren = "ImageMapLauren.webp"
    image bg Intro01 = "Intro01.webp"
    image bg IslandPeek = "IslandPeek.webp"
    image bg JackoffClub01 = "JackoffClub01.webp"
    image bg JackoffClub02 = "JackoffClub02.webp"
    image bg JackoffClub03 = "JackoffClub03.webp"
    image bg JackoffClub04 = "JackoffClub04.webp"
    image bg JackoffClub05 = "JackoffClub05.webp"
    image bg JackoffClub06 = "JackoffClub06.webp"
    image bg JackoffClub07 = "JackoffClub07.webp"
    image bg JackoffClub08 = "JackoffClub08.webp"
    image bg Kitchen01 = "Kitchen01.webp"
    image bg KitchenNight = "KitchenNight.webp"
    image bg LaurenDoor = "LaurenDoor.webp"
    image bg LaurenDoorNight = "LaurenDoorNight.webp"
    image bg LaurenInBed = "LaurenInBed.webp"
    image bg LaurenInShower01 = "LaurenInShower01.webp"
    image bg LaurenInShower02 = "LaurenInShower02.webp"
    image bg LaurenMadInRoom01 = "LaurenMadInRoom01.webp"
    image bg LaurenMadInRoom02 = "LaurenMadInRoom02.webp"
    image bg LaurenMadInRoom03 = "LaurenMadInRoom03.webp"
    image bg LaurenMadInRoom04 = "LaurenMadInRoom04.webp"
    image bg LaurenMadInRoom05 = "LaurenMadInRoom05.webp"
    image bg LaurenMadInRoom06 = "LaurenMadInRoom06.webp"
    image bg LaurenMastBateBath01 = "LaurenMastBateBath01.webp"
    image bg LaurenMastBateBath02 = "LaurenMastBateBath02.webp"
    image bg LaurenNightEmpty = "LaurenNightEmpty.webp"
    image bg LaurenNightPeek1 = "LaurenNightPeek1.webp"
    image bg LaurenNightPeek2 = "LaurenNightPeek2.webp"
    image bg LaurenNightPeek3 = "LaurenNightPeek3.webp"
    image bg LaurenPonieTV = "LaurenPonieTV.webp"
    image bg LaurenRemoteSearch01 = "LaurenRemoteSearch01.webp"
    image bg LaurenRemoteSearch02 = "LaurenRemoteSearch02.webp"
    image bg LaurenRemoteSearch03 = "LaurenRemoteSearch03.webp"
    image bg LaurenRemoteSearch04 = "LaurenRemoteSearch04.webp"
    image bg LaurenRemoteSearch05 = "LaurenRemoteSearch05.webp"
    image bg LaurenRemoteSearch06 = "LaurenRemoteSearch06.webp"
    image bg LaurenRemoteSearch07 = "LaurenRemoteSearch07.webp"
    image bg LaurenRoom01 = "LaurenRoom01.webp"
    image bg LaurenSleepIn = "LaurenSleepIn.webp"
    image bg LaurensPictures01 = "LaurensPictures01.webp"
    image bg LaurenWakeMe1 = "LaurenWakeMe1.webp"
    image bg LaurenWakeMe2 = "LaurenWakeMe2.webp"
    image bg LaurenWakeMe3 = "LaurenWakeMe3.webp"
    image bg LaurenWakeMe4 = "LaurenWakeMe4.webp"
    image bg LaurenWakeMe5 = "LaurenWakeMe5.webp"
    image bg LaurenWakeMeAngry = "LaurenWakeMeAngry.webp"
    image bg LaurenWatchTV01 = "LaurenWatchTV01.webp"
    image bg LaurenWatchTV02 = "LaurenWatchTV02.webp"
    image bg LaurenWatchTV03 = "LaurenWatchTV03.webp"
    image bg LaurenWatchTV04 = "LaurenWatchTV04.webp"
    image bg LaurenWatchTV05 = "LaurenWatchTV05.webp"
    image bg LaurenWatchTV06 = "LaurenWatchTV06.webp"
    image bg LockerRoom = "LockerRoom.webp"
    image bg LockerRoom03 = "LockerRoom03.webp"
    image bg LoungeNight = "LoungeNight.webp"
    image bg Memes01 = "Meme01.png"
    image bg Memes02 = "Meme02.png"
    image bg Memes03 = "Meme03.png"
    image bg Memes04 = "Meme04.png"
    image bg Memes05 = "Meme05.webp"
    image bg Memes06 = "Meme06.webp"
    image bg Memes07 = "Meme07.webp"
    image bg Memes08 = "Meme08.webp"
    image bg MobileScreen = "MobileScreen.png"
    image bg MomCloseupDinner = "MomCloseupDinner.webp"
    image bg MomDoor = "MomDoor.webp"
    image bg MomDoorNight = "MomDoorNight.webp"
    image bg MomDrinkingKitchen01 = "MomDrinkingKitchen01.webp"
    image bg MomDrinkingKitchen02 = "MomDrinkingKitchen02.webp"
    image bg MomDrinkingKitchen03 = "MomDrinkingKitchen03.webp"
    image bg MomDrinkingKitchen04 = "MomDrinkingKitchen04.webp"
    image bg MomDrinkingKitchen05 = "MomDrinkingKitchen05.webp"
    image bg MomInBedAtNight = "MomInBedAtNight.webp"
    image bg MomInShower01 = "MomInShower01.webp"
    image bg MomInShower02 = "MomInShower02.webp"
    image bg MomMadInRoom01 = "MomMadInRoom01.webp"
    image bg MomMadInRoom02 = "MomMadInRoom02.webp"
    image bg MomMadInRoom03 = "MomMadInRoom03.webp"
    image bg MomMadInRoom04 = "MomMadInRoom04.webp"
    image bg MomMadInRoom05 = "MomMadInRoom05.webp"
    image bg MomMadInRoom06 = "MomMadInRoom06.webp"
    image bg MomMastBateBath01 = "MomMastBateBath01.webp"
    image bg MomMastBateBath02 = "MomMastBateBath02.webp"
    image bg MomMastBateBath03 = "MomMastBateBath03.webp"
    image bg MomOffice01 = "MomOffice01.webp"
    image bg MomOffice02 = "MomOffice02.webp"
    image bg MomOffice03 = "MomOffice03.webp"
    image bg MomOffice04 = "MomOffice04.webp"
    image bg MomOffice05 = "MomOffice05.webp"
    image bg MomOffice06 = "MomOffice06.webp"
    image bg MomOffice07 = "MomOffice07.webp"
    image bg MomOffice08 = "MomOffice08.webp"
    image bg MomOffice09 = "MomOffice09.webp"
    image bg MomOffice10 = "MomOffice10.webp"
    image bg MomSleepIsland = "MomSleepIsland.webp"
    image bg MomSleepKitchen = "MomSleepKitchen.webp"
    image bg MomsPictures01 = "MomsPictures01.webp"
    image bg MomsRoom = "MomsRoom.webp"
    image bg MomRoomNight = "MomRoomNight.webp"
    image bg MomsTitts01 = "MomsTitts01.jpg"
    image bg MomThinkingRobe01 = "MomThinkingRobe01.jpg"
    image bg MomWorriedRobe01 = "MomWorriedRobe01.webp"
    image bg MyRoomNight = "MyRoomNight.webp"
    image bg MyRoomNightWSidney = "MyRoomNightWSidney.webp"
    image bg NewClassroom01 = "NewClassroom01.webp"
    image bg NewClassroom02 = "NewClassroom02.webp"
    image bg NewClassroom03 = "NewClassroom03.webp"
    image bg NewClassroom04 = "NewClassroom04.webp"
    image bg NewClassroom05 = "NewClassroom05.webp"
    image bg NightLauren01 = "NightLauren01.webp"
    image bg NightSneakMom01 = "NightSneakMom01.webp"
    image bg NightSneakMom02 = "NightSneakMom02.webp"
    image bg NTRClub01 = "NTRClub01.webp"
    image bg NTRClub02 = "NTRClub02.webp"
    image bg NTRClub03 = "NTRClub03.webp"
    image bg NTRClub04 = "NTRClub04.webp"
    image bg NTRClub05 = "NTRClub05.webp"
    image bg NTRClub06 = "NTRClub06.webp"
    image bg NTRClub07 = "NTRClub07.webp"
    image bg NTRClub08 = "NTRClub08.webp"
    image bg NTRClub09 = "NTRClub09.webp"
    image bg NTRClub10 = "NTRClub10.webp"
    image bg NTRClub11 = "NTRClub11.webp"
    image bg NTRClub12 = "NTRClub12.webp"
    image bg NTRClub13 = "NTRClub13.webp"
    image bg NTRClub14 = "NTRClub14.webp"
    image bg NTRClub15 = "NTRClub15.webp"
    image bg NTRClub16 = "NTRClub16.webp"
    image bg NTRClub17 = "NTRClub17.webp"
    image bg NTRClub18 = "NTRClub18.webp"
    image bg NTRClub19 = "NTRClub19.webp"
    image bg NTRClub20 = "NTRClub20.webp"
    image bg NTRClub21 = "NTRClub21.webp"
    image bg NTRClub22 = "NTRClub22.webp"
    image bg NTRClub23 = "NTRClub23.webp"
    image bg NTRClub24 = "NTRClub24.webp"
    image bg NTRClub25 = "NTRClub25.webp"
    image bg NTRClub26 = "NTRClub26.webp"
    image bg NTRClub27 = "NTRClub27.webp"
    image bg NTRClub28 = "NTRClub28.webp"
    image bg NTRClub29 = "NTRClub29.webp"
    image bg NTRClub30 = "NTRClub30.webp"
    image bg OnPhone02 = "OnPhone02.webp"
    image bg OnPhoneBed01 = "OnPhoneBed01.jpg"
    image bg PeekCaught01 = "PeekCaught01.webp"
    image bg PeekCaught02 = "PeekCaught02.webp"
    image bg PeekJack01 = "PeekJack01.webp"
    image bg PeekJack02 = "PeekJack02.webp"
    image bg PeekJack03 = "PeekJack03.webp"
    image bg PeekJack04 = "PeekJack04.webp"
    image bg PeekSidneyDressing01 = "PeekSidneyDressing01.webp"
    image bg PeekSidneyDressing02 = "PeekSidneyDressing02.webp"
    image bg PeekSidneyDressing03 = "PeekSidneyDressing03.webp"
    image bg PeekSidneyDressing04 = "PeekSidneyDressing04.webp"
    image bg PeekSidneyDressing05 = "PeekSidneyDressing05.webp"
    image bg PeekSidneyDressing06 = "PeekSidneyDressing06.webp"
    image bg PeekSidneyDressing07 = "PeekSidneyDressing07.webp"
    image bg PeekSidneyDressing08 = "PeekSidneyDressing08.webp"
    image bg PeekSidneyDressing09 = "PeekSidneyDressing09.webp"
    image bg PeekSidneyDressing10 = "PeekSidneyDressing10.webp"
    image bg PeekSidneyDressing11 = "PeekSidneyDressing11.webp"
    image bg PeekSidneyDressing12 = "PeekSidneyDressing12.webp"
    image bg RoomClimaxLauren = "RoomClimaxLauren.webp"
    image bg RoomClimaxMom = "RoomClimaxMom.webp"
    image bg RoomClimaxSidney = "RoomClimaxSidney.webp"
    image bg RoomCumWackLauren01 = "RoomCumWackLauren01.webp"
    image bg RoomCumWackLauren02 = "RoomCumWackLauren02.webp"
    image bg RoomCumWackMom01 = "RoomCumWackMom01.webp"
    image bg RoomCumWackMom02 = "RoomCumWackMom02.webp"
    image bg RoomCumWackSidney01 = "RoomCumWackSidney01.webp"
    image bg RoomCumWackSidney02 = "RoomCumWackSidney02.webp"
    image bg RoomDDreamLauren01 = "RoomDDreamLauren01.webp"
    image bg RoomDDreamLauren02 = "RoomDDreamLauren02.webp"
    image bg RoomDDreamLauren03 = "RoomDDreamLauren03.webp"
    image bg RoomDDreamLauren04 = "RoomDDreamLauren04.webp"
    image bg RoomDDreamMom01 = "RoomDDreamMom01.webp"
    image bg RoomDDreamMom02 = "RoomDDreamMom02.webp"
    image bg RoomDDreamMom03 = "RoomDDreamMom03.webp"
    image bg RoomDDreamMom04 = "RoomDDreamMom04.webp"
    image bg RoomDDreamMom05 = "RoomDDreamMom05.webp"
    image bg RoomDDreamSidney01 = "RoomDDreamSidney01.webp"
    image bg RoomDDreamSidney02 = "RoomDDreamSidney02.webp"
    image bg RoomDDreamSidney03 = "RoomDDreamSidney03.webp"
    image bg RoomDDreamSidney04 = "RoomDDreamSidney04.webp"
    image bg RoomDDreamSidney05 = "RoomDDreamSidney05.webp"
    image bg RoomWackoffLauren01 = "RoomWackoffLauren01.webp"
    image bg RoomWackoffLauren02 = "RoomWackoffLauren02.webp"
    image bg RoomWackoffLauren03 = "RoomWackoffLauren03.webp"
    image bg RoomWackoffLauren04 = "RoomWackoffLauren04.webp"
    image bg RoomWackoffLauren05 = "RoomWackoffLauren05.webp"
    image bg RoomWackoffMom01 = "RoomWackoffMom01.webp"
    image bg RoomWackoffMom02 = "RoomWackoffMom02.webp"
    image bg RoomWackoffMom03 = "RoomWackoffMom03.webp"
    image bg RoomWackoffMom04 = "RoomWackoffMom04.webp"
    image bg RoomWackoffMom05 = "RoomWackoffMom05.webp"
    image bg RoomWackoffSidney01 = "RoomWackoffSidney01.webp"
    image bg RoomWackoffSidney02 = "RoomWackoffSidney02.webp"
    image bg RoomWackoffSidney03 = "RoomWackoffSidney03.webp"
    image bg RoomWackoffSidney04 = "RoomWackoffSidney04.webp"
    image bg RoomWackoffSidney05 = "RoomWackoffSidney05.webp"
    image bg RyanDishes = "RyanDishes.webp"
    image bg RyanHomework01 = "RyanHomework01.webp"
    image bg RyanHomework02 = "RyanHomework02.webp"
    image bg RyanHomework03 = "RyanHomework03.webp"
    image bg RyanHomework04 = "RyanHomework04.webp"
    image bg RyansRoom01 = "RyansRoom01.jpg"
    image bg SafeTitleWAttributions = "SafeTitleWAttributions.webp"
    image bg SafeWarningIntro = "SafeWarningIntro.webp"
    image bg SchoolBathBlow01 = "SchoolBathBlow01.webp"
    image bg SchoolBathBlow02 = "SchoolBathBlow02.webp"
    image bg SchoolBathBlow03 = "SchoolBathBlow03.webp"
    image bg SchoolBathBlow04 = "SchoolBathBlow04.webp"
    image bg SchoolBathBlow05 = "SchoolBathBlow05.webp"
    image bg SchoolBathBlow06 = "SchoolBathBlow06.webp"
    image bg SchoolBathBlow07 = "SchoolBathBlow07.webp"
    image bg SchoolBathBlow08 = "SchoolBathBlow08.webp"
    image bg SchoolBathBlow09 = "SchoolBathBlow09.webp"
    image bg SchoolBathBlow10 = "SchoolBathBlow10.webp"
    image bg SchoolBathBlow11 = "SchoolBathBlow11.webp"
    image bg SchoolBathBlow12 = "SchoolBathBlow12.webp"
    image bg SchoolBathBlow13 = "SchoolBathBlow13.webp"
    image bg SchoolBathBlow14 = "SchoolBathBlow14.webp"
    image bg SchoolBathBlow15 = "SchoolBathBlow15.webp"
    image bg SchoolBathBlow16 = "SchoolBathBlow16.webp"
    image bg SchoolBathroom01 = "SchoolBathroom01.webp"
    image bg SchoolHallway01 = "SchoolHallway01.webp"
    image bg SCLaurenHornyBathDoor = "SCLaurenHornyBathDoor.webp"
    image bg SCLaurenShowerBathDoor = "SCLaurenShowerBathDoor.webp"
    image bg SCMomHornyBathDoor = "SCMomHornyBathDoor.webp"
    image bg SCMomShowerBathDoor = "SCMomShowerBathDoor.webp"
    image bg SCSidneyHornyBathDoor = "SCSidneyHornyBathDoor.webp"
    image bg SCSidneyShowerBathDoor = "SCSidneyShowerBathDoor.webp"
    image bg SidneyAngry01 = "SidneyAngry01.webp"
    image bg SidneyAngry02 = "SidneyAngry02.webp"
    image bg SidneyAngry03 = "SidneyAngry03.webp"
    image bg SidneyAngry04 = "SidneyAngry04.webp"
    image bg SidneyAngry05 = "SidneyAngry05.webp"
    image bg SidneyAngry06 = "SidneyAngry06.webp"
    image bg SidneyComesHome01 = "SidneyComesHome01.webp"
    image bg SidneyComesHome02 = "SidneyComesHome02.webp"
    image bg SidneyComesHome03 = "SidneyComesHome03.webp"
    image bg SidneyComesHome04 = "SidneyComesHome04.webp"
    image bg SidneyComesHome05 = "SidneyComesHome05.webp"
    image bg SidneyComesHome06 = "SidneyComesHome06.webp"
    image bg SidneyComesHome07 = "SidneyComesHome07.webp"
    image bg SidneyInKitchen = "SidneyInKitchen.webp"
    image bg SidneyInShower01 = "SidneyInShower01.webp"
    image bg SidneyInShower02 = "SidneyInShower02.webp"
    image bg SidneyKitchen01 = "SidneyKitchen01.webp"
    image bg SidneyKitchen02 = "SidneyKitchen02.webp"
    image bg SidneyKitchen03 = "SidneyKitchen03.webp"
    image bg SidneyKitchen04 = "SidneyKitchen04.webp"
    image bg SidneyKitchen05 = "SidneyKitchen05.webp"
    image bg SidneyKitchen06 = "SidneyKitchen06.webp"
    image bg SidneyKitchen07 = "SidneyKitchen07.webp"
    image bg SidneyKitchen08 = "SidneyKitchen08.webp"
    image bg SidneyLaurenSleep01 = "SidneyLaurenSleep01.webp"
    image bg SidneyLaurenSleeping01 = "SidneyLaurenSleeping01.webp"
    image bg SidneyLaurenSneak01 = "SidneyLaurenSneak01.webp"
    image bg SidneyLaurenSneak02 = "SidneyLaurenSneak02.webp"
    image bg SidneyLaurenSneak03 = "SidneyLaurenSneak03.webp"
    image bg SidneyLaurenSneak04 = "SidneyLaurenSneak04.webp"
    image bg SidneyLaurenSneak05 = "SidneyLaurenSneak05.webp"
    image bg SidneyLaurenSneak06 = "SidneyLaurenSneak06.webp"
    image bg SidneyLaurenSneak07 = "SidneyLaurenSneak07.webp"
    image bg SidneyLaurenSneak08 = "SidneyLaurenSneak08.webp"
    image bg SidneyLaurenSneak09 = "SidneyLaurenSneak09.webp"
    image bg SidneyLaurenSneak10 = "SidneyLaurenSneak10.webp"
    image bg SidneyLaurenSneak11 = "SidneyLaurenSneak11.webp"
    image bg SidneyLaurenSneak12 = "SidneyLaurenSneak12.webp"
    image bg SidneyLaurenSneak13 = "SidneyLaurenSneak13.webp"
    image bg SidneyLaurenSneak14 = "SidneyLaurenSneak14.webp"
    image bg SidneyLaurenSneak15 = "SidneyLaurenSneak15.webp"
    image bg SidneyLaurenSneak16 = "SidneyLaurenSneak16.webp"
    image bg SidneyLaurenSneak17 = "SidneyLaurenSneak17.webp"
    image bg SidneyLaurenSneak18 = "SidneyLaurenSneak18.webp"
    image bg SidneyLaurenSneak19 = "SidneyLaurenSneak19.webp"
    image bg SidneyLaurenSneak20 = "SidneyLaurenSneak20.webp"
    image bg SidneyLaurenSneak21 = "SidneyLaurenSneak21.webp"
    image bg SidneyLaurenSneak22 = "SidneyLaurenSneak22.webp"
    image bg SidneyLaurenSneak23 = "SidneyLaurenSneak23.webp"
    image bg SidneyLaurenSneak24 = "SidneyLaurenSneak24.webp"
    image bg SidneyLaurenSneak25 = "SidneyLaurenSneak25.webp"
    image bg SidneyLaurenSneak26 = "SidneyLaurenSneak26.webp"
    image bg SidneyLoungeMorning = "SidneyLoungeMorning.webp"
    image bg SidneyLoungeNight = "SidneyLoungeNight.webp"
    image bg SidneyMastBateBath01 = "SidneyMastBateBath01.webp"
    image bg SidneyMastBateBath02 = "SidneyMastBateBath02.webp"
    image bg SidneysPictures01 = "SidneysPictures01.webp"
    image bg SidneySleepIn01 = "SidneySleepIn01.webp"
    image bg SleepBlack = "SleepBlack.jpg"
    image bg SleepWithSidney01 = "SleepWithSidney01.webp"
    image bg SleepWithSidney02 = "SleepWithSidney02.webp"
    image bg SleepWithSidney03 = "SleepWithSidney03.webp"
    image bg SleepWithSidney04 = "SleepWithSidney04.webp"
    image bg SleepWithSidney05 = "SleepWithSidney05.webp"
    image bg SleepWithSidney06 = "SleepWithSidney06.webp"
    image bg SleepWithSidney07 = "SleepWithSidney07.webp"
    image bg SleepWithSidney08 = "SleepWithSidney08.webp"
    image bg SleepWithSidney09 = "SleepWithSidney09.webp"
    image bg SleepWithSidney10 = "SleepWithSidney10.webp"
    image bg SleepWithSidney11 = "SleepWithSidney11.webp"
    image bg SleepWithSidney12 = "SleepWithSidney12.webp"
    image bg SleepWithSidney13 = "SleepWithSidney13.webp"
    image bg SleepWithSidney14 = "SleepWithSidney14.webp"
    image bg SleepWithSidney15 = "SleepWithSidney15.webp"
    image bg SleepWithSidney16 = "SleepWithSidney16.webp"
    image bg SleepWithSidney17 = "SleepWithSidney17.webp"
    image bg SleepWithSidney18 = "SleepWithSidney18.webp"
    image bg SleepWithSidney19 = "SleepWithSidney19.webp"
    image bg SleepWithSidney20 = "SleepWithSidney20.webp"
    image bg SleepWithSidney21 = "SleepWithSidney21.webp"
    image bg SleepWithSidney22 = "SleepWithSidney22.webp"
    image bg SleepWithSidney23 = "SleepWithSidney23.webp"
    image bg SleepWithSidney24 = "SleepWithSidney24.webp"
    image bg SleepWithSidney25 = "SleepWithSidney25.webp"
    image bg SleepWithSidney26 = "SleepWithSidney26.webp"
    image bg SleepWithSidney27 = "SleepWithSidney27.webp"
    image bg SleepWithSidney28 = "SleepWithSidney28.webp"
    image bg SleepWithSidney29 = "SleepWithSidney29.webp"
    image bg SleepWithSidney30 = "SleepWithSidney30.webp"
    image bg SleepWithSidney31 = "SleepWithSidney31.webp"
    image bg SleepWithSidney32 = "SleepWithSidney32.webp"
    image bg SleepWithSidney33 = "SleepWithSidney33.webp"
    image bg SleepWithSidney34 = "SleepWithSidney34.webp"
    image bg SleepWithSidney35 = "SleepWithSidney35.webp"
    image bg SleepWithSidney36 = "SleepWithSidney36.webp"
    image bg SleepWithSidney37 = "SleepWithSidney37.webp"
    image bg SleepWithSidney38 = "SleepWithSidney38.webp"
    image bg SleepWithSidney39 = "SleepWithSidney39.webp"
    image bg SleepWithSidney40 = "SleepWithSidney40.webp"
    image bg SleepWithSidney41 = "SleepWithSidney41.webp"
    image bg SleepWithSidney42 = "SleepWithSidney42.webp"
    image bg SleepWithSidney43 = "SleepWithSidney43.webp"
    image bg SpikeTheTea01 = "SpikeTheTea01.webp"
    image bg SpikeTheTea02 = "SpikeTheTea02.webp"
    image bg SpyCamBath01 = "SpyCamBath01.webp"
    image bg SpyCamBath02 = "SpyCamBath02.webp"
    image bg SpyCamBath03 = "SpyCamBath03.webp"
    image bg SpyCamBath04 = "SpyCamBath04.webp"
    image bg SpyCamLaurenBedroom01 = "SpyCamLaurenBedroom01.webp"
    image bg SpyCamLaurenBedroom02 = "SpyCamLaurenBedroom02.webp"
    image bg SpyCamLaurenBedroom03 = "SpyCamLaurenBedroom03.webp"
    image bg SpyCamLaurenBedroom04 = "SpyCamLaurenBedroom04.webp"
    image bg SpyCamLaurenBedroom05 = "SpyCamLaurenBedroom05.webp"
    image bg SpyCamLaurenBedroom06 = "SpyCamLaurenBedroom06.webp"
    image bg SpyCamLaurenBedroom07 = "SpyCamLaurenBedroom07.webp"
    image bg SpyCamLaurenBedroom08 = "SpyCamLaurenBedroom08.webp"
    image bg SpyCamLaurenBedroom09 = "SpyCamLaurenBedroom09.webp"
    image bg SpyCamLaurenBedroom10 = "SpyCamLaurenBedroom10.webp"
    image bg SpyCamLaurenBedroom11 = "SpyCamLaurenBedroom11.webp"
    image bg SpyCamLaurenBedroom12 = "SpyCamLaurenBedroom12.webp"
    image bg SpyCamLaurenBedroom13 = "SpyCamLaurenBedroom13.webp"
    image bg SpyCamLaurenBedroom14 = "SpyCamLaurenBedroom14.webp"
    image bg SpyCamLaurenBedroom15 = "SpyCamLaurenBedroom15.webp"
    image bg SpyCamLaurenBedroom16 = "SpyCamLaurenBedroom16.webp"
    image bg SpyCamLaurenBedroom17 = "SpyCamLaurenBedroom17.webp"
    image bg SpyCamLaurenBedroom18 = "SpyCamLaurenBedroom18.webp"
    image bg SpyCamLaurenBedroom19 = "SpyCamLaurenBedroom19.webp"
    image bg SpyCamLaurenBedroom20 = "SpyCamLaurenBedroom20.webp"
    image bg SpyCamLaurenBedroom21 = "SpyCamLaurenBedroom21.webp"
    image bg SpyCamLaurenBedroom22 = "SpyCamLaurenBedroom22.webp"
    image bg SpyCamMomBedroom01 = "SpyCamMomBedroom01.webp"
    image bg SpyCamMomBedroom02 = "SpyCamMomBedroom02.webp"
    image bg SpyCamMomBedroom03 = "SpyCamMomBedroom03.webp"
    image bg SpyCamMomBedroom04 = "SpyCamMomBedroom04.webp"
    image bg SpyCamMomBedroom05 = "SpyCamMomBedroom05.webp"
    image bg SpyCamMomBedroom06 = "SpyCamMomBedroom06.webp"
    image bg SpyCamMomBedroom07 = "SpyCamMomBedroom07.webp"
    image bg SpyCamMomBedroom08 = "SpyCamMomBedroom08.webp"
    image bg SpyCamMomBedroom09 = "SpyCamMomBedroom09.webp"
    image bg SpyCamMomBedroom10 = "SpyCamMomBedroom10.webp"
    image bg SpyCamMomBedroom11 = "SpyCamMomBedroom11.webp"
    image bg SpyCamMomBedroom12 = "SpyCamMomBedroom12.webp"
    image bg SpyCamMomBedroom13 = "SpyCamMomBedroom13.webp"
    image bg SpyCamMomBedroom14 = "SpyCamMomBedroom14.webp"
    image bg SpyCamMomBedroom15 = "SpyCamMomBedroom15.webp"
    image bg SpyCamMomBedroom16 = "SpyCamMomBedroom16.webp"
    image bg SpyCamMomBedroom17 = "SpyCamMomBedroom17.webp"
    image bg SpyCamMomBedroom18 = "SpyCamMomBedroom18.webp"
    image bg SpyCamMomBedroom19 = "SpyCamMomBedroom19.webp"
    image bg SpyCamMomBedroom20 = "SpyCamMomBedroom20.webp"
    image bg SpyCamMomBedroom21 = "SpyCamMomBedroom21.webp"
    image bg SpyCamSidneyBedroom01 = "SpyCamSidneyBedroom01.webp"
    image bg SpyCamSidneyBedroom02 = "SpyCamSidneyBedroom02.webp"
    image bg SpyCamSidneyBedroom03 = "SpyCamSidneyBedroom03.webp"
    image bg SpyCamSidneyBedroom04 = "SpyCamSidneyBedroom04.webp"
    image bg SpyCamSidneyBedroom05 = "SpyCamSidneyBedroom05.webp"
    image bg SpyCamSidneyBedroom06 = "SpyCamSidneyBedroom06.webp"
    image bg SpyCamSidneyBedroom07 = "SpyCamSidneyBedroom07.webp"
    image bg SpyCamSidneyBedroom08 = "SpyCamSidneyBedroom08.webp"
    image bg SpyCamSidneyBedroom09 = "SpyCamSidneyBedroom09.webp"
    image bg SpyCamSidneyBedroom10 = "SpyCamSidneyBedroom10.webp"
    image bg StreetNight = "StreetNight.webp"
    image bg streets = "Streets.jpg"
    image bg StripCaught = "StripCaught.webp"
    image bg StripCaught02 = "StripCaught02.webp"
    image bg StripCaught03 = "StripCaught03.webp"
    image bg StripCaught04 = "StripCaught04.webp"
    image bg StripCaught05 = "StripCaught05.webp"
    image bg StripPeek001 = "StripPeek001.webp"
    image bg StripPeek01 = "StripPeek01.webp"
    image bg StripperPole01 = "StripperPole01.webp"
    image bg StripperPole02 = "StripperPole02.webp"
    image bg StripperPole03 = "StripperPole03.webp"
    image bg StripperPole04 = "StripperPole04.webp"
    image bg StripperPole05 = "StripperPole05.webp"
    image bg StripperPole06 = "StripperPole06.webp"
    image bg StripperPole07 = "StripperPole07.webp"
    image bg TitleWAttributions = "TitleWAttributions.webp"
    image bg WakeUp01 = "WakeUp01.jpg"
    image bg Wakeup02 = "WakeUp02.webp"
    image bg WalkingBar = "WalkingBar.webp"
    image bg WalkingCasino = "WalkingCasino.webp"
    image bg warehouse = "Warehouse.jpg"
    image bg WarningIntro = "WarningIntro.webp"

    image 01Bobbynormal = "01Bobbynormal.webp"
    image 02Bobbylookup = "02Bobbylookup.webp"
    image 03Bobbythink = "03Bobbythink.webp"
    image 04Bobbyconcerned = "04Bobbyconcerned.webp"
    image Afternoon = "Afternoon.png"
    image CamaraFlash = "CameraFlash.webp"
    image Deliveries01 = "Deliveries01.webp"
    image Deliveries02 = "Deliveries02.webp"
    image Deliveries03 = "Deliveries03.webp"
    image Deliveries04 = "Deliveries04.webp"
    image Deliveries05 = "Deliveries05.webp"
    image Deliveries06 = "Deliveries06.webp"
    image Evening = "Evening.png"
    image LateMorning = "LateMorning.png"
    image Memes01 = "Meme01.png"
    image Memes02 = "Meme02.png"
    image Memes03 = "Meme03.png"
    image Memes04 = "Meme04.png"
    image Memes05 = "Meme05.webp"
    image Memes06 = "Meme06.webp"
    image Memes07 = "Meme07.webp"
    image Memes08 = "Meme08.webp"
    image Morning = "Morning.png"
    image Night = "Night.png"
    image travel01 = "travel01.webp"
    image travel02 = "travel02.webp"
    image travel03 = "travel03.webp"
    image travel04 = "travel04.webp"
    image travel05 = "travel05.webp"
    image travel06 = "travel06.webp"
