msgid ""
msgstr ""
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: a-family-venture\n"
"X-Crowdin-Project-ID: 492487\n"
"X-Crowdin-Language: it\n"
"X-Crowdin-File: /[DonRP.AFV] main/game/tl/crowdin/options.po\n"
"X-Crowdin-File-ID: 1351\n"
"Project-Id-Version: a-family-venture\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Language-Team: Italian\n"
"Language: it_IT\n"
"PO-Revision-Date: 2022-02-20 15:04\n"

msgid "A Family Venture"
msgstr "Una Venture di famiglia"

