msgid ""
msgstr ""
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Crowdin-Project: a-family-venture\n"
"X-Crowdin-Project-ID: 492487\n"
"X-Crowdin-Language: fr\n"
"X-Crowdin-File: /[DonRP.AFV] main/game/tl/crowdin/options.po\n"
"X-Crowdin-File-ID: 1351\n"
"Project-Id-Version: a-family-venture\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Language-Team: French\n"
"Language: fr_FR\n"
"PO-Revision-Date: 2022-04-23 09:34\n"

# TODO: Translation updated at 2022-04-23 HH:HH# XXtranslate crowdin strings:XX# XX## game/options.rpy:15
msgid "A Family Venture"
msgid_plural "Ignore this. translate only: One"
msgstr[0] ""
msgstr[1] ""

